/*
 * Copyright (C) Neil Rahilly <neilrahilly@gmail.com>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.i18n.phonenumbers;

import com.google.i18n.phonenumbers.Phonemetadata.NumberFormat;
import com.google.i18n.phonenumbers.Phonemetadata.PhoneMetadata;
import com.google.i18n.phonenumbers.Phonemetadata.PhoneMetadataCollection;
import com.google.i18n.phonenumbers.Phonemetadata.PhoneNumberDesc;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Formatter;
import java.util.List;
import java.util.Map;

/**
 * Tool to convert phone number metadata from the XML format to Python.
 * (Based on the same tool for JavaScript by Nikolaos Trogkanis.)
 *
 * @author Neil Rahilly
 */
public class BuildMetadataPythonFromXml {

  private static final String HELP_MESSAGE =
      "Usage:\n" +
      "BuildMetadataPythonFromXml <inputFile> <outputFile> [<liteBuild>]\n" +
      "\n" +
      "where:\n" +
      "  inputFile    The input file containing phone number metadata in XML format.\n" +
      "  outputFile   The output file to contain phone number metadata in JSON format.\n" +
      "  liteBuild    Whether to generate the lite-version of the metadata (default:\n" +
      "               false). When set to true certain metadata will be omitted.\n" +
      "               At this moment, example numbers information is omitted.\n" +
      "\n" +
      "Example command line invocation:\n" +
      "BuildMetadataPythonFromXml PhoneNumberMetadata.xml metadatalite.py true\n";

  static final String COPYRIGHT_NOTICE =
      "# Copyright (C) Neil Rahilly <neilrahilly@gmail.com>\n" +
      "#\n" +
      "# Licensed under the Apache License, Version 2.0 (the \"License\");\n" +
      "# you may not use this file except in compliance with the License.\n" +
      "# You may obtain a copy of the License at\n" +
      "#\n" +
      "# http://www.apache.org/licenses/LICENSE-2.0\n" +
      "#\n" +
      "# Unless required by applicable law or agreed to in writing, software\n" +
      "# distributed under the License is distributed on an \"AS IS\" BASIS,\n" +
      "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n" +
      "# See the License for the specific language governing permissions and\n" +
      "# limitations under the License.\n\n\n";

  private static final String FILE_OVERVIEW =
      "\"\"\"Generated by BuildMetadataPythonFromXml.java. Do not edit!\"\"\"\n\n";

  private static final String COUNTRY_CODE_TO_REGION_CODE_MAP_COMMENT =
      "# A mapping from a country code to the region codes which denote the\n" +
      "# country/region represented by that country code. In the case of multiple\n" +
      "# countries sharing a calling code, such as the NANPA countries, the one\n" +
      "# indicated with \"is_main_country_for_code\" in the metadata should be first.\n";

  private static final String COUNTRY_TO_METADATA_COMMENT =
      "# A mapping from a region code to the PhoneMetadata for that region.\n";

  public static void main(String[] args) throws Exception {
    if (args.length != 2 && args.length != 3) {
      System.err.println(HELP_MESSAGE);
      System.exit(1);
    }
    String inputFile = args[0];
    String outputFile = args[1];
    boolean liteBuild = args.length > 2 && args[2].equals("true");

    PhoneMetadataCollection metadataCollection =
        BuildMetadataFromXml.buildPhoneMetadataCollection(inputFile, liteBuild);
    Map<Integer, List<String>> countryCodeToRegionCodeMap =
        BuildMetadataFromXml.buildCountryCodeToRegionCodeMap(metadataCollection);

    BufferedWriter writer = new BufferedWriter(new FileWriter(outputFile));

    writer.write(COPYRIGHT_NOTICE);
    Formatter formatter = new Formatter(writer);
    formatter.format(FILE_OVERVIEW, inputFile);

    writer.write(COUNTRY_CODE_TO_REGION_CODE_MAP_COMMENT);
    writer.write("country_code_to_region_code_map = ");
    writeCountryCodeCodeToRegionCodeMap(countryCodeToRegionCodeMap, writer);
    writer.write("\n\n");

    writer.write(COUNTRY_TO_METADATA_COMMENT);
    writer.write("country_to_metadata = ");
    writeCountryToMetadataMap(metadataCollection, writer);
    writer.write("\n\n");

    writer.flush();
    writer.close();
  }

  // Writes a PhoneMetadataCollection in JSON format.
  private static void writeCountryToMetadataMap(PhoneMetadataCollection metadataCollection,
                                                BufferedWriter writer) throws IOException {
    writer.write("{\n");
    boolean isFirstTimeInLoop = true;
    for (PhoneMetadata metadata : metadataCollection.getMetadataList()) {
      if (isFirstTimeInLoop) {
        isFirstTimeInLoop = false;
      } else {
        writer.write(",");
      }
      String regionCode = metadata.getId();
      PythonArrayBuilder pythonArrayBuilder = new PythonArrayBuilder();
      toJsArray(metadata, pythonArrayBuilder);
      writer.write("\"");
      writer.write(regionCode);
      writer.write("\":");
      writer.write(pythonArrayBuilder.toString());
    }
    writer.write("}");
  }

  // Writes a Map<Integer, List<String>> in JSON format.
  private static void writeCountryCodeCodeToRegionCodeMap(
      Map<Integer, List<String>> countryCodeToRegionCodeMap,
      BufferedWriter writer) throws IOException {
    writer.write("{\n");
    boolean isFirstTimeInLoop = true;
    for (Map.Entry<Integer, List<String>> entry : countryCodeToRegionCodeMap.entrySet()) {
      if (isFirstTimeInLoop) {
        isFirstTimeInLoop = false;
      } else {
        writer.write(",");
      }
      writer.write(Integer.toString(entry.getKey()));
      writer.write(":");
      PythonArrayBuilder pythonArrayBuilder = new PythonArrayBuilder();
      pythonArrayBuilder.beginArray();
      pythonArrayBuilder.appendIterator(entry.getValue().iterator());
      pythonArrayBuilder.endArray();
      writer.write(pythonArrayBuilder.toString());
    }
    writer.write("}");
  }

  // Converts NumberFormat to PythonArray.
  private static void toJsArray(NumberFormat format, PythonArrayBuilder pythonArrayBuilder) {
    pythonArrayBuilder.beginArray();

    // missing 0
    pythonArrayBuilder.append(null);
    // required string pattern = 1;
    pythonArrayBuilder.append(format.getPattern());
    // required string format = 2;
    pythonArrayBuilder.append(format.getFormat());
    // repeated string leading_digits_pattern = 3;
    int leadingDigitsPatternSize = format.getLeadingDigitsPatternCount();
    if (leadingDigitsPatternSize > 0) {
      pythonArrayBuilder.beginArray();
      for (int i = 0; i < leadingDigitsPatternSize; i++) {
        pythonArrayBuilder.append(format.getLeadingDigitsPattern(i));
      }
      pythonArrayBuilder.endArray();
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string national_prefix_formatting_rule = 4;
    if (format.hasNationalPrefixFormattingRule()) {
      pythonArrayBuilder.append(format.getNationalPrefixFormattingRule());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string domestic_carrier_code_formatting_rule = 5;
    if (format.hasDomesticCarrierCodeFormattingRule()) {
      pythonArrayBuilder.append(format.getDomesticCarrierCodeFormattingRule());
    } else {
      pythonArrayBuilder.append(null);
    }

    pythonArrayBuilder.endArray();
  }

  // Converts PhoneNumberDesc to PythonArray.
  private static void toJsArray(PhoneNumberDesc desc, PythonArrayBuilder pythonArrayBuilder) {
    pythonArrayBuilder.beginArray();

    // missing 0
    pythonArrayBuilder.append(null);
    // missing 1
    pythonArrayBuilder.append(null);
    // optional string national_number_pattern = 2;
    if (desc.hasNationalNumberPattern()) {
      pythonArrayBuilder.append(desc.getNationalNumberPattern());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string possible_number_pattern = 3;
    if (desc.hasPossibleNumberPattern()) {
      pythonArrayBuilder.append(desc.getPossibleNumberPattern());
    } else {
      pythonArrayBuilder.append(null);
    }
    // missing 4
    pythonArrayBuilder.append(null);
    // missing 5
    pythonArrayBuilder.append(null);
    // optional string example_number = 6;
    if (desc.hasExampleNumber()) {
      pythonArrayBuilder.append(desc.getExampleNumber());
    } else {
      pythonArrayBuilder.append(null);
    }

    pythonArrayBuilder.endArray();
  }

  // Converts PhoneMetadata to PythonArray.
  private static void toJsArray(PhoneMetadata metadata, PythonArrayBuilder pythonArrayBuilder) {
    pythonArrayBuilder.beginArray();

    // missing 0
    pythonArrayBuilder.append(null);
    // required PhoneNumberDesc general_desc = 1;
    if (metadata.hasGeneralDesc()) {
      toJsArray(metadata.getGeneralDesc(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc fixed_line = 2;
    if (metadata.hasFixedLine()) {
      toJsArray(metadata.getFixedLine(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc mobile = 3;
    if (metadata.hasMobile()) {
      toJsArray(metadata.getMobile(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc toll_free = 4;
    if (metadata.hasTollFree()) {
      toJsArray(metadata.getTollFree(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc premium_rate = 5;
    if (metadata.hasPremiumRate()) {
      toJsArray(metadata.getPremiumRate(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc shared_cost = 6;
    if (metadata.hasSharedCost()) {
      toJsArray(metadata.getSharedCost(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc personal_number = 7;
    if (metadata.hasPersonalNumber()) {
      toJsArray(metadata.getPersonalNumber(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc voip = 8;
    if (metadata.hasVoip()) {
      toJsArray(metadata.getVoip(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // required string id = 9;
    pythonArrayBuilder.append(metadata.getId());
    // required int32 country_code = 10;
    pythonArrayBuilder.append(metadata.getCountryCode());
    // required string international_prefix = 11;
    pythonArrayBuilder.append(metadata.getInternationalPrefix());

    // optional string national_prefix = 12;
    if (metadata.hasNationalPrefix()) {
      pythonArrayBuilder.append(metadata.getNationalPrefix());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string preferred_extn_prefix = 13;
    if (metadata.hasPreferredExtnPrefix()) {
      pythonArrayBuilder.append(metadata.getPreferredExtnPrefix());
    } else {
      pythonArrayBuilder.append(null);
    }
    // missing 14
    pythonArrayBuilder.append(null);
    // optional string national_prefix_for_parsing = 15;
    if (metadata.hasNationalPrefixForParsing()) {
      pythonArrayBuilder.append(metadata.getNationalPrefixForParsing());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string national_prefix_transform_rule = 16;
    if (metadata.hasNationalPrefixTransformRule()) {
      pythonArrayBuilder.append(metadata.getNationalPrefixTransformRule());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string preferred_international_prefix = 17;
    if (metadata.hasPreferredInternationalPrefix()) {
      pythonArrayBuilder.append(metadata.getPreferredInternationalPrefix());
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional bool same_mobile_and_fixed_line_pattern = 18 [default=false];
    if (metadata.getSameMobileAndFixedLinePattern()) {
      pythonArrayBuilder.append(1);
    } else {
      pythonArrayBuilder.append(null);
    }
    // repeated NumberFormat number_format = 19;
    int numberFormatSize = metadata.getNumberFormatCount();
    if (numberFormatSize > 0) {
      pythonArrayBuilder.beginArray();
      for (int i = 0; i < numberFormatSize; i++) {
        toJsArray(metadata.getNumberFormat(i), pythonArrayBuilder);
      }
      pythonArrayBuilder.endArray();
    } else {
      pythonArrayBuilder.append(null);
    }
    // repeated NumberFormat intl_number_format = 20;
    int intlNumberFormatSize = metadata.getIntlNumberFormatCount();
    if (intlNumberFormatSize > 0) {
      pythonArrayBuilder.beginArray();
      for (int i = 0; i < intlNumberFormatSize; i++) {
        toJsArray(metadata.getIntlNumberFormat(i), pythonArrayBuilder);
      }
      pythonArrayBuilder.endArray();
    } else {
      pythonArrayBuilder.append(null);
    }
    // required PhoneNumberDesc pager = 21;
    if (metadata.hasPager()) {
      toJsArray(metadata.getPager(), pythonArrayBuilder);
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional bool main_country_for_code = 22 [default=false];
    if (metadata.getMainCountryForCode()) {
      pythonArrayBuilder.append(1);
    } else {
      pythonArrayBuilder.append(null);
    }
    // optional string leading_digits = 23;
    if (metadata.hasLeadingDigits()) {
      pythonArrayBuilder.append(metadata.getLeadingDigits());
    } else {
      pythonArrayBuilder.append(null);
    }

    pythonArrayBuilder.endArray();
  }
}
