# Copyright (C) 2011 Neil Rahilly <neilrahilly@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""This file is automatically generated by buildmetadataprotofromxml.py. Do
not modify directly."""


# A mapping from a country code to the region codes which denote the
# country/region represented by that country code. In the case of multiple
# countries sharing a calling code, such as the NANPA countries, the one
# indicated with "is_main_country_for_code" in the metadata should be first.
country_code_to_region_code_map_test = {1: ['US', 'BS'],
 39: ['IT'],
 44: ['GB'],
 48: ['PL'],
 49: ['DE'],
 52: ['MX'],
 54: ['AR'],
 61: ['AU'],
 64: ['NZ'],
 65: ['SG'],
 81: ['JP'],
 82: ['KR'],
 244: ['AO'],
 262: ['RE', 'YT'],
 376: ['AD']}
