#!/usr/bin/env python
# Copyright (C) 2011 Neil Rahilly <neilrahilly@gmail.com>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tool to convert phone number metadata from the XML format to protocol 
buffer format. (Based on the Java version.)
"""

import logging
import optparse
import os.path
import pprint

from phonenumbers import buildmetadatafromxml
from phonenumbers import phonemetadata_pb2
from phonenumbers import phonenumberutil
from phonenumbers.test import phonenumberutil_test


USAGE = """Example command line invocation:
./buildmetadataprotofromxml.py -tl -i PhoneNumberMetadata.xml -o data"""


COPYRIGHT_NOTICE = """\
# Copyright (C) 2011 Neil Rahilly <neilrahilly@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License")
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""

MODULE_COMMENT = '''\
"""This file is automatically generated by buildmetadataprotofromxml.py. Do
not modify directly."""


'''

MAPPING_COMMENT = """\
# A mapping from a country code to the region codes which denote the
# country/region represented by that country code. In the case of multiple
# countries sharing a calling code, such as the NANPA countries, the one
# indicated with "is_main_country_for_code" in the metadata should be first.
"""


def main():
    parser = optparse.OptionParser(USAGE)
    parser.add_option("-i", "--input-file", dest="input_file",
            help="The input file containing phone number metadata in XML "
                 "format.")
    parser.add_option("-o", "--output-dir", dest="output_dir",
            help="The output directory to store phone number metadata in "
                 "proto format (one file per region) and the country code to "
                 "region code mapping file.")
    parser.add_option("-t", "--for-testing", dest="for_testing", 
            action="store_true", default=False,
            help="Flag whether to generate metadata for testing purposes or "
                 "not (default: false).")
    parser.add_option("-l", "--lite-build", dest="lite_build", 
            action="store_true", default=False,
            help="Whether to generate the lite-version of the metadata "
                 "(default: false). When set to true certain metadata will "
                 "be omitted. At this moment, example numbers information is "
                 "omitted.")
    parser.add_option("-v", "--verbose", dest="verbose", 
            action="store_true", default=False,
            help="Log debug information (default: false).")
    options, args = parser.parse_args()
    options.input_file = os.path.abspath(options.input_file)
    options.output_dir = os.path.abspath(options.output_dir)
    if options.verbose:
        logging.basicConfig(level=logging.DEBUG)
    logging.debug("parsed options: %s" % options)

    metadata_collection = buildmetadatafromxml.build_phone_metadata_collection(
            options.input_file, options.lite_build)
    
    _generate_metadata_proto_files(metadata_collection, options)
    _write_country_calling_code_mapping_to_python_file(metadata_collection,
            options)


def _generate_metadata_proto_files(metadata_collection, options):
    # Generate metadata proto files
    if options.for_testing:
        file_prefix = os.path.join(options.output_dir, "data",
                phonenumberutil_test.TEST_META_DATA_FILE_PREFIX)
    else:
        file_prefix = os.path.join(options.output_dir, "data",
                phonenumberutil.META_DATA_FILE_PREFIX)
    logging.debug("file_prefix: %s" % file_prefix)

    for metadata in metadata_collection.metadata:
        region_code = metadata.id
        out_metadata_collection = phonemetadata_pb2.PhoneMetadataCollection()
        out_metadata_collection.metadata.add().CopyFrom(metadata)
        output_filename = file_prefix + "_" + region_code
        logging.debug("writing file: %s" % output_filename)
        output_for_region = open(output_filename, "wb")
        output_for_region.write(
                out_metadata_collection.SerializeToString())
        output_for_region.close()
    return metadata_collection
    

def _write_country_calling_code_mapping_to_python_file(metadata_collection,
                                                       options):
    country_code_to_region_code_map = \
            buildmetadatafromxml.build_country_code_to_region_code_map(
                    metadata_collection)
    mapping_name = phonenumberutil.COUNTRY_CODE_TO_REGION_CODE_MAP_NAME
    module_name = mapping_name.replace("_", "")
    if options.for_testing:
        mapping_name += "_test"
    module_name += ".py"
    mapping_file_name = os.path.join(options.output_dir, module_name)

    logging.debug("%s = %s" % (mapping_name, country_code_to_region_code_map))
    logging.debug("writing to %s" % mapping_file_name)
    
    mapping_file = open(mapping_file_name, "w")
    mapping_file.write(COPYRIGHT_NOTICE) 
    mapping_file.write(MODULE_COMMENT) 
    mapping_file.write(MAPPING_COMMENT)
    mapping_file.write("%s = " % mapping_name)
    pprint.pprint(country_code_to_region_code_map, mapping_file)
    mapping_file.close()


if __name__ == "__main__":
    main()
